# Generated by Django 6.0.5 on 2026-07-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minimall", "0006_order_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待付款"),
                    ("paid", "已付款"),
                    ("shipped", "已发货"),
                    ("received", "已收货"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                    ("refunded", "已退款"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
