# Generated by Django 6.0.5 on 2026-07-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minimall", "0008_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="账户余额"
            ),
        ),
    ]
