# Generated by Django 6.0.5 on 2026-07-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minimall", "0011_add_avatar_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="头像更新时间"
            ),
        ),
    ]
