# Generated by Django 6.0.5 on 2026-07-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minimall", "0012_add_avatar_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="图片更新时间"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_version",
            field=models.PositiveIntegerField(default=1, verbose_name="图片版本号"),
        ),
    ]
