# Generated by Django 6.0.5 on 2026-08-13 00:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("minimall", "0015_add_product_sort_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "类别", "verbose_name_plural": "类别"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "用户-扩展", "verbose_name_plural": "用户-扩展"},
        ),
    ]
