# Generated by Django 6.0.5 on 2026-09-21 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minimall", "0017_update_media_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="退款时间"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待付款"),
                    ("paid", "已付款"),
                    ("shipped", "已发货"),
                    ("received", "已收货"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                    ("refunding", "退款中"),
                    ("refunded", "已退款"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "待处理"),
                            ("approved", "已批准"),
                            ("rejected", "已驳回"),
                            ("refunded", "已退款"),
                        ],
                        default="requested",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="买家申请时不带金额, 管理员批准时必填 (协商金额)",
                        max_digits=10,
                        null=True,
                        verbose_name="退款金额",
                    ),
                ),
                (
                    "order_status_before",
                    models.CharField(
                        choices=[
                            ("pending", "待付款"),
                            ("paid", "已付款"),
                            ("shipped", "已发货"),
                            ("received", "已收货"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                            ("refunding", "退款中"),
                            ("refunded", "已退款"),
                        ],
                        help_text="申请那一刻的快照, 驳回时用它恢复订单状态",
                        max_length=20,
                        verbose_name="申请前订单状态",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="批准时写明协商结果, 驳回时是原因",
                        verbose_name="管理员备注",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="批准时间"
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="打款时间"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="驳回时间"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="minimall.order",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "退款申请",
                "verbose_name_plural": "退款申请",
                "db_table": "minimall_refund_request",
                "ordering": ["-created_at"],
            },
        ),
    ]
