# Generated by Django 6.0.5 on 2026-10-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minimall", "0018_order_refunded_at_alter_order_status_refundrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "slug",
                    models.SlugField(
                        help_text="chunk 主键用它拼 ({slug}-{序号}), 写英文短标识",
                        max_length=60,
                        unique=True,
                        verbose_name="稳定标识",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("policy", "政策"),
                            ("shipping", "配送"),
                            ("aftersale", "售后"),
                            ("payment", "支付"),
                            ("order", "订单"),
                            ("product", "商品说明"),
                        ],
                        default="policy",
                        help_text="给后续过滤留的口; 会随 chunk 一起进索引的 metadata",
                        max_length=20,
                        verbose_name="分类标签",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="索引按 Markdown 结构切分; 不用写一级标题",
                        verbose_name="正文(Markdown)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="下架即不进索引 (重跑一次索引脚本会被物理剔除)",
                        verbose_name="是否启用",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="排序(越小越靠前)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "知识文章",
                "verbose_name_plural": "知识文章",
                "db_table": "minimall_knowledge_article",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
