# Generated by Django 6.0.5 on 2026-07-27 17:13

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minimall", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="URL 别名")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="minimall.category",
                        verbose_name="上级分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品分类",
                "verbose_name_plural": "商品分类",
                "db_table": "minimall_category",
            },
        ),
    ]
