# Generated by Django 6.0.5 on 2026-07-27 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minimall", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="商品名称")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="URL 别名"
                    ),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="商品描述")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="价格"),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="库存")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否上架")),
                ("is_featured", models.BooleanField(default=False, verbose_name="是否推荐")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="minimall.category",
                        verbose_name="所属分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "db_table": "minimall_product",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="products/", verbose_name="图片")),
                ("is_primary", models.BooleanField(default=False, verbose_name="是否主图")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="minimall.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品图片",
                "verbose_name_plural": "商品图片",
                "db_table": "minimall_product_image",
                "ordering": ["sort_order"],
            },
        ),
    ]
