# Generated by Django 6.0.5 on 2026-07-27 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minimall", "0004_cart_cartitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("receiver_name", models.CharField(max_length=100, verbose_name="收货人")),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                ("province", models.CharField(max_length=50, verbose_name="省")),
                ("city", models.CharField(max_length=50, verbose_name="市")),
                ("district", models.CharField(max_length=50, verbose_name="区")),
                ("detail", models.TextField(verbose_name="详细地址")),
                ("is_default", models.BooleanField(default=False, verbose_name="默认地址")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "收货地址",
                "verbose_name_plural": "收货地址",
                "db_table": "minimall_shipping_address",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
