# Generated by Django 6.0.5 on 2026-07-27 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minimall", "0007_alter_order_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "订单明细", "verbose_name_plural": "订单明细"},
        ),
        migrations.AlterField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="取消时间"),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_no",
            field=models.CharField(max_length=32, unique=True, verbose_name="订单号"),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="付款时间"),
        ),
        migrations.AlterField(
            model_name="order",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="收货时间"),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="发货时间"),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address_snapshot",
            field=models.JSONField(verbose_name="收货地址快照"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待付款"),
                    ("paid", "已付款"),
                    ("shipped", "已发货"),
                    ("received", "已收货"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                    ("refunded", "已退款"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="总金额"),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="minimall.order",
                verbose_name="订单",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="minimall.product",
                verbose_name="商品",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(max_length=200, verbose_name="商品名称"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="商品单价"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="数量"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="小计"),
        ),
    ]
