# Generated by Django 6.0.5 on 2026-07-28 11:52

from django.db import migrations, models

import minimall.models


class Migration(migrations.Migration):
    dependencies = [
        ("minimall", "0009_profile_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="is_primary",
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=minimall.models.product_image_upload_to, verbose_name="图片"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=minimall.models.avatar_upload_to,
                verbose_name="头像",
            ),
        ),
    ]
