# Generated by Django 6.0.5 on 2026-07-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minimall", "0010_remove_is_primary_and_custom_upload_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_version",
            field=models.PositiveIntegerField(default=1, verbose_name="头像版本号"),
        ),
    ]
