"""CharAgent: 从零手写 AI Agent 运行时框架 (十个包, 公共 API 汇聚导出).

一句话理解: 本文件是**框架的门脸** —— 想用这个框架的人只 import 一次
`CharAgent`, 就能拿到全部对外公共 API, 不必记住「哪个东西在哪个子包里」.
各子包自己也各有一份门面 (`CharAgent.checkpoint.__all__` 等), 本文件是它们的
合集, 不新造 API.

汇聚的十一个包 (P0 的八个 + 后来补的 `prompt` / `redact` / `structured_logging`;
职责见下表).
(框架另外还有三个包 —— `client` / `server` / `eval` —— 刻意不在这里, 见下面第四条)

| 包 | 一句话 |
|----|--------|
| `model` | 薄 ChatModel 协议 + httpx 裸调 / openai SDK 双适配器 |
| `tool` | @tool 装饰器 + JSON schema 自动生成 + 可操作错误语义 |
| `agent` | 手写 agent loop (并行工具 / 错误自纠错 / 循环防护 / 截断处理) |
| `stream` | 流式事件总线 (九类事件 + seq + 四条状态机不变量) |
| `hooks` | hook 注册表骨架 (六个触发点, 空注册零开销; 工具执行前那个可拒绝) |
| `retry` | 重试退避 + 幂等键 (包在 ChatModel 协议层, loop 零改动) |
| `checkpoint` | 快照序列化协议 + 内存 / Redis / Postgres 三实现 + 断点续跑 |
| `db` | 五实体数据模型 + 表定义 + alembic 迁移 + 仓储 |
| `prompt` | 提示词集中存放与按名加载 (`templates/*.prompt` + `load_prompt`) |
| `redact` | 日志脱敏 (四条通用打码规则 + 业务声明的字段路径) |
| `structured_logging` | 结构化日志 (一处出口 + 打码工序 + 三个 id 贯穿) |

四条刻意的排除 (不是漏了, 理由各不同):

1. **`tool` (小写, 那个 @tool 装饰器) 不在顶层导出** —— 它与子包
   `CharAgent.tool` 同名, 导出会遮蔽包属性, 于是 `from CharAgent.tool import
   tool` 成了唯一写法. 其余名字没有这个冲突.
2. **`client` 不入本文件** —— 它是**应用入口** (`python -m CharAgent.client`), 不是
   库 API: 没有人会 `from CharAgent import main`. 想跑演示直接敲那条命令.
3. **`server` 也不入本文件** —— 它是框架的 HTTP + SSE 服务层 (**可选依赖组**
   `charagent[server]`, 要 web 栈). 门面的承诺是「装了这个包就能用」, 而本框架
   的立身之本是零 web 依赖: 把 fastapi 变成 import `CharAgent` 的硬要求, 等于
   让只想用 agent loop 的人先装一个 web 框架. 要用 HTTP 的写
   `from CharAgent.server import create_app` 并装上那个 extra —— 这条纪律由用例
   守着 (`tests/test_root_facade.py` 起子进程验「import 根门面不会拖上 web 栈」).
4. **`eval` 也不入本文件** —— 离线跑分那层要**真 API key** 才跑得动 (它专门打真
   模型), 与上面两条同属「要额外条件才能用」. 跑分与回看写
   `from CharAgent.eval import EvalRunner`, 命令行是
   `python -m CharAgent.eval compare a.json b.json`.

为什么现在才汇聚 (历史): 各包的门面一直是齐的, 根门面却长期只导出了
model + tool —— 各处都记着「agent / stream / hooks / retry / checkpoint / db
尚未顶层导出, 同批处理」, 几轮都往后推, 一直没做. 收尾时 (P0 验收线) 把它一次
补完, 并加了一条防漂移用例 (`tests/test_root_facade.py`: 子包 __all__ 里的每个
名字, 根门面都必须有).
"""

from __future__ import annotations

# --- agent: 手写 agent loop + 循环防护 + 上下文压缩 ------------------------
from CharAgent.agent import (
    APPROVAL_REJECTED_TEXT,
    AgentLoop,
    Approval,
    ApprovalRequest,
    CalibratedTokenCounter,
    CompactionConfigError,
    CompactionPolicy,
    CompiledView,
    GuardConfigError,
    LoopConfigError,
    LoopGuard,
    LoopOutcome,
    LoopResult,
    RunContext,
    TokenCounter,
    ToolCallFact,
    ToolCallOutcome,
    ToolProvider,
    TraceSink,
    TrimAndSummarize,
    TruncationStrategy,
    TurnRecord,
)

# --- checkpoint: 快照协议 + 三实现 + 断点续跑 ------------------------------
from CharAgent.checkpoint import (
    BACKEND_NAMES,
    DEFAULT_CODEC,
    SCHEMA_VERSION,
    Checkpoint,
    CheckpointCapabilities,
    CheckpointCapabilityError,
    CheckpointCodec,
    CheckpointConfigError,
    CheckpointError,
    CheckpointMetadata,
    CheckpointMigrationError,
    CheckpointSaver,
    CheckpointSerializationError,
    CheckpointSource,
    CheckpointState,
    CheckpointStorageError,
    InMemoryCheckpointSaver,
    PostgresCheckpointSaver,
    RedisCheckpointSaver,
    Suspension,
    build_saver,
    check_identifier,
    checkpoint_saver_from_env,
    format_history,
    migrate_body,
    pending_tool_calls,
    postgres_dsn,
    summarize,
)

# --- db: 五实体数据模型 + 表定义 + 仓储 ------------------------------------
from CharAgent.db import (
    ALL_TABLES,
    ALLOWED_TRANSITIONS,
    RUN_STATUS_FOR_OUTCOME,
    SETTLEABLE_RUN_STATUSES,
    TABLE_NAMES,
    TERMINAL_RUN_STATUSES,
    CheckpointRow,
    ConversationRecorder,
    CostGap,
    CostLine,
    Database,
    DataConfigError,
    DataStoreError,
    DbError,
    InvalidTransitionError,
    Message,
    MessageRole,
    MessagesRepository,
    PeakRule,
    PgDatabase,
    PgIdempotencyStore,
    PgRepository,
    PriceTable,
    PricingNotReadyError,
    Run,
    RunCost,
    RunRecorder,
    RunsRepository,
    RunStatus,
    Thread,
    ThreadsRepository,
    ThreadStatus,
    TierPrices,
    TierVerdict,
    ToolCall,
    ToolCallsRepository,
    ToolCallStatus,
    ToolCallSummary,
    TranscriptLine,
    TurnPair,
    assistant_answer,
    build_tool_call,
    can_transition,
    checkpoints,
    conversation_turns,
    cost_of,
    count_visible,
    echo_enabled,
    ensure_pricing_ready,
    ensure_transition,
    has_visible_answer,
    load_pricing,
    message_id_for,
    messages,
    metadata,
    model_to_dict,
    recorded_transcript,
    run_status_for_outcome,
    runs,
    sqlalchemy_url,
    threads,
    title_for,
    tool_calls,
    visible_transcript,
)

# --- hooks: hook 注册表骨架 (扩展点) ---------------------------------------
from CharAgent.hooks import (
    Decision,
    HookConfigError,
    HookError,
    HookFailure,
    HookFn,
    HookPoint,
    HookRegistry,
    ModelCallPhase,
    Verdict,
)

# --- model: ChatModel 协议 + 双适配器 --------------------------------------
from CharAgent.model import (
    ChatModel,
    DeltaCallback,
    FinishReason,
    HttpXChatModel,
    ModelConfigError,
    ModelConnectionError,
    ModelError,
    ModelErrorKind,
    ModelMessage,
    ModelProtocolError,
    ModelResponse,
    ModelStatusError,
    ModelTimeoutError,
    ModelToolCall,
    OpenAIChatModel,
    ToolSpec,
    Usage,
    chat_model_from_env,
    openai_chat_model_from_env,
)

# --- prompt: 提示词集中存放与按名加载 (difficulties #69) -------------------
#
# 除了「按名字取正文」, 还有身份说明的**引用**那一组 (prompt/ref.py): 它让快照
# 不必逐帧抄那几千字正文 (帧 v5), 而由会话层按引用补回来. 那组函数是框架内部
# 两级 (client/session.py 与 checkpoint/serialization.py) 在用的接口, 按本门面
# 的规矩 (子包 __all__ 里的名字都在这里出现) 一并上浮.
from CharAgent.prompt import (
    IDENTITY_ROLE,
    PromptError,
    PromptNotFoundError,
    PromptRef,
    PromptRefMismatchError,
    PromptVariableError,
    deref_prompt,
    detach_identity,
    detach_view_identity,
    identity_message,
    load_prompt,
    prompt_ref,
    ref_name,
    resolve_model_name,
    restore_identity,
)

# --- redact: 日志脱敏 (通用规则 + 业务声明的字段路径) -----------------------
from CharAgent.redact import (
    MASK_RULES,
    WIPE,
    WIPED,
    Mask,
    RedactConfigError,
    RedactError,
    Redactor,
    RuleRedactor,
    mask_text,
)

# --- retry: 重试退避 + 熔断 failover + 幂等键 ------------------------------
from CharAgent.retry import (
    CircuitBreaker,
    CircuitOpenError,
    CircuitPolicy,
    CircuitState,
    ClaimResult,
    ClaimStatus,
    FailoverChatModel,
    IdempotencyKey,
    IdempotencyKeyError,
    IdempotencyStore,
    InMemoryIdempotencyStore,
    ModelSwitch,
    RetryAttempt,
    RetryCallback,
    RetryConfigError,
    RetryError,
    RetryingChatModel,
    RetryPolicy,
    ServingRecord,
    SwitchCallback,
    current_serving,
    is_retryable,
    retry_async,
    serving_scope,
)

# --- stream: 流式事件总线 --------------------------------------------------
from CharAgent.stream import (
    TERMINAL_TYPES,
    TOOL_RESULT_SUMMARY_LIMIT,
    EventBus,
    EventSequenceError,
    EventSink,
    EventType,
    StreamError,
    StreamEvent,
)

# --- structured_logging: 结构化日志 + 三个 id 贯穿 (difficulties #38) -------
# 出口 (`configure_logging`) 与取号 (`get_logger`) 在 config 里, 三个 id 与
# `log_context` 在 context 里 —— 门面把两半一起上浮, 因为它们是一件事的两面
# (打日志的人既要拿到 logger, 也要让那一行带上号)
from CharAgent.structured_logging import (
    ID_FIELDS,
    LOGGER_ROOT,
    JsonFormatter,
    LoggingConfigError,
    LoggingError,
    PlainFormatter,
    RedactFilter,
    TraceBinding,
    TraceIds,
    configure_logging,
    current_ids,
    get_logger,
    log_context,
)

# --- tool: @tool 装饰器 + schema 生成 --------------------------------------
# 注意: 装饰器 `tool` 刻意不在本文件导入 (会遮蔽子包 CharAgent.tool, 见模块 docstring)
from CharAgent.tool import (
    Tool,
    ToolActionableError,
    ToolConfigError,
    ToolError,
    ToolExecution,
    ToolSchemaInfo,
    ToolTimeoutError,
    build_manual_schema,
    build_pydantic_schema,
    execute_tool,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "ALL_TABLES",
    "APPROVAL_REJECTED_TEXT",
    "BACKEND_NAMES",
    "DEFAULT_CODEC",
    "IDENTITY_ROLE",
    "ID_FIELDS",
    "LOGGER_ROOT",
    "MASK_RULES",
    "RUN_STATUS_FOR_OUTCOME",
    "SCHEMA_VERSION",
    "SETTLEABLE_RUN_STATUSES",
    "TABLE_NAMES",
    "TERMINAL_RUN_STATUSES",
    "TERMINAL_TYPES",
    "TOOL_RESULT_SUMMARY_LIMIT",
    "WIPE",
    "WIPED",
    "AgentLoop",
    "Approval",
    "ApprovalRequest",
    "CalibratedTokenCounter",
    "ChatModel",
    "Checkpoint",
    "CheckpointCapabilities",
    "CheckpointCapabilityError",
    "CheckpointCodec",
    "CheckpointConfigError",
    "CheckpointError",
    "CheckpointMetadata",
    "CheckpointMigrationError",
    "CheckpointRow",
    "CheckpointSaver",
    "CheckpointSerializationError",
    "CheckpointSource",
    "CheckpointState",
    "CheckpointStorageError",
    "CircuitBreaker",
    "CircuitOpenError",
    "CircuitPolicy",
    "CircuitState",
    "ClaimResult",
    "ClaimStatus",
    "CompactionConfigError",
    "CompactionPolicy",
    "CompiledView",
    "ConversationRecorder",
    "CostGap",
    "CostLine",
    "DataConfigError",
    "DataStoreError",
    "Database",
    "DbError",
    "Decision",
    "DeltaCallback",
    "EventBus",
    "EventSequenceError",
    "EventSink",
    "EventType",
    "FailoverChatModel",
    "FinishReason",
    "GuardConfigError",
    "HookConfigError",
    "HookError",
    "HookFailure",
    "HookFn",
    "HookPoint",
    "HookRegistry",
    "HttpXChatModel",
    "IdempotencyKey",
    "IdempotencyKeyError",
    "IdempotencyStore",
    "InMemoryCheckpointSaver",
    "InMemoryIdempotencyStore",
    "InvalidTransitionError",
    "JsonFormatter",
    "LoggingConfigError",
    "LoggingError",
    "LoopConfigError",
    "LoopGuard",
    "LoopOutcome",
    "LoopResult",
    "Mask",
    "Message",
    "MessageRole",
    "MessagesRepository",
    "ModelCallPhase",
    "ModelConfigError",
    "ModelConnectionError",
    "ModelError",
    "ModelErrorKind",
    "ModelMessage",
    "ModelProtocolError",
    "ModelResponse",
    "ModelStatusError",
    "ModelSwitch",
    "ModelTimeoutError",
    "ModelToolCall",
    "OpenAIChatModel",
    "PeakRule",
    "PgDatabase",
    "PgIdempotencyStore",
    "PgRepository",
    "PlainFormatter",
    "PostgresCheckpointSaver",
    "PriceTable",
    "PricingNotReadyError",
    "PromptError",
    "PromptNotFoundError",
    "PromptRef",
    "PromptRefMismatchError",
    "PromptVariableError",
    "RedactConfigError",
    "RedactError",
    "RedactFilter",
    "Redactor",
    "RedisCheckpointSaver",
    "RetryAttempt",
    "RetryCallback",
    "RetryConfigError",
    "RetryError",
    "RetryPolicy",
    "RetryingChatModel",
    "RuleRedactor",
    "Run",
    "RunContext",
    "RunCost",
    "RunRecorder",
    "RunStatus",
    "RunsRepository",
    "ServingRecord",
    "StreamError",
    "StreamEvent",
    "Suspension",
    "SwitchCallback",
    "Thread",
    "ThreadStatus",
    "ThreadsRepository",
    "TierPrices",
    "TierVerdict",
    "TokenCounter",
    "Tool",
    "ToolActionableError",
    "ToolCall",
    "ToolCallFact",
    "ToolCallOutcome",
    "ToolCallStatus",
    "ToolCallSummary",
    "ToolCallsRepository",
    "ToolConfigError",
    "ToolError",
    "ToolExecution",
    "ToolProvider",
    "ToolSchemaInfo",
    "ToolSpec",
    "ToolTimeoutError",
    "TraceBinding",
    "TraceIds",
    "TraceSink",
    "TranscriptLine",
    "TrimAndSummarize",
    "TruncationStrategy",
    "TurnPair",
    "TurnRecord",
    "Usage",
    "Verdict",
    "assistant_answer",
    "build_manual_schema",
    "build_pydantic_schema",
    "build_saver",
    "build_tool_call",
    "can_transition",
    "chat_model_from_env",
    "check_identifier",
    "checkpoint_saver_from_env",
    "checkpoints",
    "configure_logging",
    "conversation_turns",
    "cost_of",
    "count_visible",
    "current_ids",
    "current_serving",
    "deref_prompt",
    "detach_identity",
    "detach_view_identity",
    "echo_enabled",
    "ensure_pricing_ready",
    "ensure_transition",
    "execute_tool",
    "format_history",
    "get_logger",
    "has_visible_answer",
    "identity_message",
    "is_retryable",
    "load_pricing",
    "load_prompt",
    "log_context",
    "mask_text",
    "message_id_for",
    "messages",
    "metadata",
    "migrate_body",
    "model_to_dict",
    "openai_chat_model_from_env",
    "pending_tool_calls",
    "postgres_dsn",
    "prompt_ref",
    "recorded_transcript",
    "ref_name",
    "resolve_model_name",
    "restore_identity",
    "retry_async",
    "run_status_for_outcome",
    "runs",
    "serving_scope",
    "sqlalchemy_url",
    "summarize",
    "threads",
    "title_for",
    "tool_calls",
    "visible_transcript",
]
