# Generated by Django 6.0.5 on 2026-08-22 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CharplotProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp", models.PositiveIntegerField(default=0, verbose_name="经验值")),
                ("level", models.PositiveIntegerField(default=1, verbose_name="等级")),
                (
                    "streak",
                    models.PositiveIntegerField(default=0, verbose_name="当前连胜"),
                ),
                (
                    "max_streak",
                    models.PositiveIntegerField(default=0, verbose_name="最大连胜"),
                ),
                (
                    "hearts",
                    models.PositiveIntegerField(default=5, verbose_name="心动值"),
                ),
                (
                    "coins",
                    models.PositiveIntegerField(default=0, verbose_name="学习币"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charplot_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "CharPlot 用户扩展",
                "verbose_name_plural": "CharPlot 用户扩展",
                "db_table": "charplot_profile",
            },
        ),
    ]
