# Generated by Django 6.0.5 on 2026-08-22 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charplot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="charplotprofile",
            name="freeze_until",
            field=models.DateField(
                blank=True, null=True, verbose_name="连胜冻结截止日期"
            ),
        ),
        migrations.AddField(
            model_name="charplotprofile",
            name="last_study_date",
            field=models.DateField(blank=True, null=True, verbose_name="最后学习日期"),
        ),
        migrations.CreateModel(
            name="CharplotUserEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("level_clear", "通关"),
                            ("answer", "答题"),
                        ],
                        max_length=32,
                        verbose_name="事件类型",
                    ),
                ),
                ("event_date", models.DateField(verbose_name="事件日期")),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="附加数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charplot_user_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "CharPlot 用户事件",
                "verbose_name_plural": "CharPlot 用户事件",
                "db_table": "charplot_user_event",
                "ordering": ["-event_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "event_type", "event_date"],
                        name="idx_user_event_type_date",
                    )
                ],
            },
        ),
    ]
