# Generated by Django 6.0.5 on 2026-08-22 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.charplot.models


class Migration(migrations.Migration):
    dependencies = [
        ("charplot", "0002_charplotprofile_freeze_until_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CharplotJourney",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("text", "纯文本"),
                            ("file", "文件"),
                            ("link", "网页链接"),
                        ],
                        max_length=16,
                        verbose_name="输入类型",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="输入内容")),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app.charplot.models.journey_file_upload_to,
                        verbose_name="源文件",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "生成中"),
                            ("ready", "已就绪"),
                            ("failed", "生成失败"),
                        ],
                        default="generating",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "graph",
                    models.JSONField(blank=True, default=dict, verbose_name="图谱快照"),
                ),
                (
                    "latest_task_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="最近任务 ID"
                    ),
                ),
                (
                    "cleared",
                    models.BooleanField(default=False, verbose_name="是否已通关"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="失败原因"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charplot_journeys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "CharPlot 学习旅程",
                "verbose_name_plural": "CharPlot 学习旅程",
                "db_table": "charplot_journey",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CharplotChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("summary", models.TextField(blank=True, verbose_name="概述")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="序号")),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="charplot.charplotjourney",
                        verbose_name="旅程",
                    ),
                ),
            ],
            options={
                "verbose_name": "CharPlot 章节",
                "verbose_name_plural": "CharPlot 章节",
                "db_table": "charplot_chapter",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CharplotKnowledgePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("summary", models.TextField(blank=True, verbose_name="概述")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="序号")),
                (
                    "error_score",
                    models.PositiveIntegerField(default=0, verbose_name="易错分"),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_points",
                        to="charplot.charplotchapter",
                        verbose_name="章节",
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dependents",
                        to="charplot.charplotknowledgepoint",
                        verbose_name="前置依赖",
                    ),
                ),
            ],
            options={
                "verbose_name": "CharPlot 知识点",
                "verbose_name_plural": "CharPlot 知识点",
                "db_table": "charplot_knowledge_point",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="charplotjourney",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_journey_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="charplotchapter",
            index=models.Index(
                fields=["journey", "order"], name="idx_chapter_journey_order"
            ),
        ),
    ]
