# Generated by Django 6.0.5 on 2026-08-23 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charplot", "0003_charplotjourney_charplotchapter_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CharplotLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hearts",
                    models.PositiveIntegerField(default=5, verbose_name="剩余心动值"),
                ),
                (
                    "current_index",
                    models.PositiveIntegerField(default=0, verbose_name="下一题下标"),
                ),
                (
                    "cleared",
                    models.BooleanField(default=False, verbose_name="是否已通关"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="charplot.charplotjourney",
                        verbose_name="旅程",
                    ),
                ),
                (
                    "knowledge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="charplot.charplotknowledgepoint",
                        verbose_name="知识点",
                    ),
                ),
            ],
            options={
                "verbose_name": "CharPlot 关卡",
                "verbose_name_plural": "CharPlot 关卡",
                "db_table": "charplot_level",
                "ordering": ["knowledge_point__order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CharplotQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("choice", "选择"),
                            ("judge", "判断"),
                            ("fill", "填空"),
                        ],
                        max_length=16,
                        verbose_name="题型",
                    ),
                ),
                ("content", models.TextField(verbose_name="题干")),
                (
                    "options",
                    models.JSONField(blank=True, default=list, verbose_name="选项"),
                ),
                (
                    "answer",
                    models.JSONField(blank=True, default=list, verbose_name="标准答案"),
                ),
                ("explanation", models.TextField(blank=True, verbose_name="讲解")),
                (
                    "sources",
                    models.JSONField(blank=True, default=list, verbose_name="来源引用"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="序号")),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="charplot.charplotlevel",
                        verbose_name="关卡",
                    ),
                ),
            ],
            options={
                "verbose_name": "CharPlot 题目",
                "verbose_name_plural": "CharPlot 题目",
                "db_table": "charplot_question",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CharplotAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField(verbose_name="是否正确")),
                (
                    "user_answer",
                    models.JSONField(blank=True, default=list, verbose_name="用户作答"),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(default=0, verbose_name="耗时(秒)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charplot_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="charplot.charplotlevel",
                        verbose_name="关卡",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="charplot.charplotquestion",
                        verbose_name="题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "CharPlot 答题记录",
                "verbose_name_plural": "CharPlot 答题记录",
                "db_table": "charplot_attempt",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="charplotlevel",
            index=models.Index(
                fields=["journey", "knowledge_point"], name="idx_level_journey_kp"
            ),
        ),
        migrations.AddIndex(
            model_name="charplotquestion",
            index=models.Index(
                fields=["level", "order"], name="idx_question_level_order"
            ),
        ),
        migrations.AddIndex(
            model_name="charplotattempt",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_attempt_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="charplotattempt",
            index=models.Index(
                fields=["level", "question"], name="idx_attempt_level_question"
            ),
        ),
    ]
