# Generated by Django 6.0.5 on 2026-08-23 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charplot", "0004_charplotlevel_charplotquestion_charplotattempt_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CharplotReviewReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="公开短链"
                    ),
                ),
                (
                    "knowledge_summary",
                    models.JSONField(default=dict, verbose_name="知识总结快照"),
                ),
                ("stats", models.JSONField(default=dict, verbose_name="答题统计快照")),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="OG 标题"
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="OG 描述"
                    ),
                ),
                (
                    "og_image",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="OG 缩略图"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "journey",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_report",
                        to="charplot.charplotjourney",
                        verbose_name="旅程",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charplot_review_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "CharPlot 复盘报告",
                "verbose_name_plural": "CharPlot 复盘报告",
                "db_table": "charplot_review_report",
            },
        ),
    ]
