# Generated by Django 6.0.5 on 2026-08-23 14:59

import django.db.models.deletion
from django.db import migrations, models


def backfill_level_fields(apps, schema_editor):
    """存量关卡回填 (Issue 08): seq / chapter / questions_status.

    - seq 按 (chapter.order, kp.order) 从 1 递增, 兼容旧 ordering 语义
    - chapter = knowledge_point.chapter (boss 关迁移时不创建, 由懒创建补)
    - questions_status: 已通关或进行中 (current_index>0, 断点续答) → ready
      (stub 保留不重生成, 防答题中断); 纯 pending → pending (首次访问有机
      升级为真实题目)
    """
    level_model = apps.get_model("charplot", "CharplotLevel")
    for journey_id in level_model.objects.values_list(
        "journey_id", flat=True
    ).distinct():
        levels = list(
            level_model.objects.filter(journey_id=journey_id)
            .select_related("knowledge_point", "knowledge_point__chapter")
            .order_by("knowledge_point__chapter__order", "knowledge_point__order", "id")
        )
        for seq, level in enumerate(levels, start=1):
            level.seq = seq
            level.chapter_id = level.knowledge_point.chapter_id
            level.questions_status = (
                "ready" if (level.cleared or level.current_index > 0) else "pending"
            )
            level.save(update_fields=["seq", "chapter", "questions_status"])


class Migration(migrations.Migration):
    dependencies = [
        ("charplot", "0005_charplotreviewreport"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="charplotlevel",
            options={
                "ordering": ["seq", "id"],
                "verbose_name": "CharPlot 关卡",
                "verbose_name_plural": "CharPlot 关卡",
            },
        ),
        migrations.AddField(
            model_name="charplotknowledgepoint",
            name="last_reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最近复习时间"
            ),
        ),
        migrations.AddField(
            model_name="charplotlevel",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levels",
                to="charplot.charplotchapter",
                verbose_name="章节",
            ),
        ),
        migrations.AddField(
            model_name="charplotlevel",
            name="latest_task_id",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="最近生成任务 ID"
            ),
        ),
        migrations.AddField(
            model_name="charplotlevel",
            name="level_type",
            field=models.CharField(
                choices=[("regular", "常规"), ("boss", "Boss")],
                default="regular",
                max_length=16,
                verbose_name="关卡类型",
            ),
        ),
        migrations.AddField(
            model_name="charplotlevel",
            name="questions_status",
            field=models.CharField(
                choices=[
                    ("pending", "待生成"),
                    ("generating", "生成中"),
                    ("ready", "已就绪"),
                    ("failed", "生成失败"),
                ],
                default="pending",
                max_length=16,
                verbose_name="题目状态",
            ),
        ),
        migrations.AddField(
            model_name="charplotlevel",
            name="seq",
            field=models.PositiveIntegerField(default=0, verbose_name="旅程内序号"),
        ),
        migrations.AddField(
            model_name="charplotquestion",
            name="source_kp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="charplot.charplotknowledgepoint",
                verbose_name="来源知识点",
            ),
        ),
        migrations.AddIndex(
            model_name="charplotlevel",
            index=models.Index(fields=["journey", "seq"], name="idx_level_journey_seq"),
        ),
        migrations.RunPython(backfill_level_fields, migrations.RunPython.noop),
    ]
