# Generated by Django 6.0.5 on 2026-08-23 15:50

import django.db.models.deletion
from django.db import migrations, models

import app.charplot.models


class Migration(migrations.Migration):
    dependencies = [
        ("charplot", "0006_alter_charplotlevel_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharplotKnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="主题名")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "cover",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="封面图 URL"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("indexing", "索引中"),
                            ("ready", "已就绪"),
                            ("failed", "索引失败"),
                            ("offline", "已下线"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "collection_name",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Milvus collection 名称",
                    ),
                ),
                (
                    "latest_task_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="最近索引任务 ID"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="失败原因"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "CharPlot 知识库",
                "verbose_name_plural": "CharPlot 知识库",
                "db_table": "charplot_knowledge_base",
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="CharplotKnowledgeBaseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file",
                    models.FileField(
                        upload_to=app.charplot.models.kb_document_upload_to,
                        verbose_name="文件",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否软删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="软删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="charplot.charplotknowledgebase",
                        verbose_name="知识库",
                    ),
                ),
            ],
            options={
                "verbose_name": "CharPlot 知识库文档",
                "verbose_name_plural": "CharPlot 知识库文档",
                "db_table": "charplot_knowledge_base_document",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["knowledge_base", "is_deleted"],
                        name="idx_kb_doc_kb_deleted",
                    )
                ],
            },
        ),
    ]
