# Generated by Django 6.0.5 on 2026-08-23 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charplot", "0007_charplotknowledgebase_charplotknowledgebasedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="charplotjourney",
            name="knowledge_base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journeys",
                to="charplot.charplotknowledgebase",
                verbose_name="知识库",
            ),
        ),
        migrations.AlterField(
            model_name="charplotjourney",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("text", "纯文本"),
                    ("file", "文件"),
                    ("link", "网页链接"),
                    ("kb", "知识库"),
                ],
                max_length=16,
                verbose_name="输入类型",
            ),
        ),
    ]
