# Generated by Django 6.0.5 on 2026-08-24 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charplot", "0008_charplotjourney_knowledge_base_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CharplotQuestionFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("answer_error", "答案有误"),
                            ("content_error", "题目内容有误"),
                            ("explanation_error", "讲解有误"),
                            ("other", "其他"),
                        ],
                        default="",
                        max_length=32,
                        verbose_name="原因",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="charplot.charplotquestion",
                        verbose_name="题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charplot_question_flags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "CharPlot 题目反馈标记",
                "verbose_name_plural": "CharPlot 题目反馈标记",
                "db_table": "charplot_question_flag",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["question", "-created_at"],
                        name="idx_flag_question_created",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "user"), name="uq_flag_question_user"
                    )
                ],
            },
        ),
    ]
